aws_dbt_snowflake_project:
  outputs:
    dev:
      account: MDGPRUK-YU06335
      database: AIRBNB
      password: Chinnmaya@07051994
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: CHINNMAYA1994
      warehouse: COMPUTE_WH
  target: dev
